### ISSUE TITLE
App/Api/Controller/ShoppingController.class.php add方法错误！

### ISSUE THREAD

**Issue by Joker09** [hxxy2003/wechat_shop#16]
``` php
if ($cart_info) {
	$data['num'] = intval($cart_info['num'])+intval($num);
	//判断库存
	if (intval($check_info['num'])<=$data['num']) {
		echo json_encode(array('status'=>0,'err'=>'库存不足！'));
		exit;
	}
	$res = $shpp->where('id='.intval($cart_info['id']))->save($data);
}
```
使用save方法返回的是修改的记录的条数，所以这里的$res始终为1，而不是期待的主键值；
所以应该是增加一行
``` php
 $res = $cart_info['id']
```

**Comment by lschuangye** [comment]
加在什么地方？我用的本地测试。首页没有授权页面，所以数据库没有添加用户记录。

**Comment by chen1729** [comment]
正解。
if ($cart_info) {
	$data['num'] = intval($cart_info['num'])+intval($num);
	//判断库存
	if (intval($check_info['num'])<=$data['num']) {
		echo json_encode(array('status'=>0,'err'=>'库存不足！'));
		exit;
	}
	$res = $shpp->where('id='.intval($cart_info['id']))->save($data);
         $res = $cart_info['id'];//增加在这里
}
